[connection]
backend_url = "ws://localhost:8080"  # Local WebSocket server URL
auth_token = "local_secure_token"    # Simple token for local testing

[plugin]
plugin_url = "http://localhost:8081/webhook"  # Local plugin URL for webhooks